# Generated by Django 6.0.6 on 2026-06-23 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('villages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubDistrictCensus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_code', models.CharField(max_length=10)),
                ('subdistrict_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('population_2011', models.IntegerField()),
                ('males', models.IntegerField()),
                ('females', models.IntegerField()),
                ('area_sqkm', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sub-District Census Data',
            },
        ),
    ]
